### PR TITLE
Add shellcheck linting

### PR DESCRIPTION
**Pull request by jeffbyrnes**
This simply adds the linting.

Relates to #287

It may be best to also add the exceptions (or adjustments) to make this pass testing as-is, since the repo is in a usable state as-is.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@HaleTom perhaps you’d appreciate this 🙂

**Comment by ghthor** [comment]
Hell yes! Look at all that work to do!

Do shellcheck and shfmt play nicely together?

**Comment by HaleTom** [comment]
@ghthor I've not heard of `shfmt` before, but from a very quick inspection I see no linkage to `shellcheck`. I only see mention of formatting (eg whitespace), whereas `shellcheck` issues often affect how code executes.

I'm busy with other projects right now, but this looks pretty good overall.  I fixed a whole heap in my PR, and it's good to see that not too many are left:

Lines:
* 1 - 200: These are preamble
*  200 - 400 The guts of the problem. Assuming 5 lines per warning, that's 40 to fix.
* 400 - 820: Unused aliases. These warnings could be removed en-masse with an ignore directive at the top of a file or function

I expect that a few more will appear with resolving the 4 instances of:
```
^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang.
```

**Comment by HaleTom** [comment]
My 2c vote: I'm vehemently against adding ignore directives simply to get Travis to green again.

I believe it's far too likely that any ignores for the sake of the colour green will be forgotten. The squeaky wheel gets oiled. Personally, I'd vote that this PR stays open for some months rather than having a "faked" resolution.

**Comment by ghthor** [comment]
I agree with you @haletom about leaving this squeaky.

**Comment by HaleTom** [comment]
In #287, I made two proposals:

1. A technological one (which this PR begins to address)
1. A process / systems systems one

I cannot see how this PR addresses suggestion (2), so I assert that the comment in the top post "Closes #287" is premature or incomplete.

I respect if the consensus is that my suggestion (2) is not wanted or warranted, but need to point out that  so far it has not been addressed.

**Comment by jeffbyrnes** [comment]
Updated the description to avoid closing #287, per @HaleTom pointing out that discussion of their 2nd point is still pending.

Sorry for jumping the gun; I understood you in that issue to mean either/or with your two points.

**Comment by jeffbyrnes** [comment]
And yes, let’s be squeaky here & properly clean these up. I’ll add to this as I get a chance!

**Comment by jeffbyrnes** [comment]
This has clearly been overtaken, closing out!

**Pull request closed without merging**
