### PR TITLE
Refactor of git status

### PR DESCRIPTION
**Pull request by ghthor**
Long time coming. Let's dogfood this for a bit, but I think it'll work well. I left the legacy version in the source code for now so it's a little bit easier to hack it back in if this break anything for anyone.

### CODE REVIEW

**Comment by HaleTom** [comment]
I suggest you parse `git status -z --porcelain=v2`

**Comment by ghthor** [comment]
I agree with this. The main blocker I have here is that my ruby knowledge is pretty newbie and the syntax/concepts were tripping me up a lot just getting this into merge. I did revert this with #269 with the TODO being, learn enough ruby to parse `git status -z --porcelain=v2`. ETA, unknown, maybe I should fill out an Issue with my plan so anyone can signal that they're working on it, if I don't get to it quickly enough.

**Comment by jeffbyrnes** [comment]
I may be able to help with that; my Ruby chops are decent. I’ll try to find some time this week to check it out.

**Comment by HaleTom** [comment]
@jeffbyrnes Thanks for the offer! I'd be willing to review your code.

**Comment by jeffbyrnes** [comment]
Haven‘t yet had any bandwidth to tackle this, sorry! One day soon, I hope.

**Pull request merged**
