### PR TITLE
Declare scmb_wrapped_shell_commands as array

### LINKED ISSUE #284: Broken `scmb_wrapped_shell_commands` in ZSH
Commit a6eeebfa91e51ec7aae21f65e0df49e461a4ca68 breaks `scmb_wrapped_shell_commands` in ZSH. It makes the loop make only one iteration with `cmd` being equal to `scmb_wrapped_shell_commands`.
The workaround is to write `scmb_wrapped_shell_commands` in the config not as a string but as an array.

### LINKED ISSUE #297: Shell commands stopped getting wrapped
Recently, built-in shell commands stopped working for my with scm_breeze. Debugging my way around, I found the culprit to be the following line in my ".git.scmbrc" file:

https://github.com/scmbreeze/scm_breeze/blob/8f5693f3452dbfa181da073bf3090c9b92614a61/git.scmbrc.example#L127

What started happening for me (and sadly I cannot say why) is that instead of wrapping each of the commands in `scmb_wrapped_shell_commands` my shell treated the entire string as a single command to try and wrap, which unsurprisingly didn't work.

When I changed that line to:
```
scmb_wrapped_shell_commands=(vim emacs gedit cat rm cp mv ln cd ls less subl code)
```
Everything started working again.

I'd submit a pull request but this is the sort of thing that I suspect might only work for a specific set of environments and not others. If anyone has sufficient shell-fu to handle this that would be great, however.

### LINKED ISSUE #315: ohmyzsh & numbered shortcuts not working
Just switched from `bash` to `zsh` shell, and using `ohmyzsh`

Have installed `scm_breeze` and it's working, and numbering files, e.g.,:
```
gs

# On branch: master...origin/master  |  [*] => $e*
#
➤ Untracked files
#
#      untracked: [1] foo 
#      untracked: [2] foo2 
#
```

But wrapped commands that make use of those numbers don't work:
```
rm 1-2
rm: cannot remove '1-2': No such file or directory
```

Variables are set properly though:
```
echo $e1 $e2
/home/stephen/code/REDACTED/foo /home/stephen/code/REDACTED/foo2
```

Version info:
```
zsh --version
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
```

Any ideas?

### PR DESCRIPTION
**Pull request by Stephen2**
Closes #315
Closes #297
Closes #284

### CODE REVIEW

**Comment by Stephen2** [comment]
I don't have knowledge of how to test this thoroughly.

But it works in `bash` and it fixes `zsh` for wrapping the commands

Thought I'd throw it up for review in case there's nothing else to it

**Comment by wrightak** [comment]
I've made these changes locally. Would be great to merge for the sake of new users.

**Comment by Stephen2** [comment]
Excellent! Thanks @jeffbyrnes for the notification, and @ghthor for the other fix :)

**Comment by ghthor** [comment]
1. #331 I think actually doesn't work and I refocused on getting some CI set back up to make sure the tests are working.

This PR might actually be the correct way to do it. I'm actively working on this

**Comment by Stephen2** [comment]
NP! I'll not delete the branch, in case you wanna reopen or anything, all yours

**Pull request closed without merging**
