### PR TITLE
Windows compat

### PR DESCRIPTION
**Pull request by AsaAyers**
Fixes scm_breeze/#135

I'm trying to use the version of bash that comes with git. These are the changes I had to make so far.

### CODE REVIEW

**Comment by AsaAyers** [comment]
The number expansion is broken now and I don't know why. if I try to use the numbers `rm 1` it becomes `/bin/rm1` and then tries to execute whatever file I was pointing at.

**Comment by AsaAyers** [comment]
https://github.com/AsaAyers/scm_breeze/blob/windows-compat/lib/git/branch_shortcuts.sh#L24

When scm_breeze invokes ruby, it's subprocess isn't running bash so /bin/git doesn't exist. It needs to somehow find `c:\Program Files (x86)\Git\cmd\git.exe` instead.

**Comment by zommerfelds** [comment]
I don't have the exact same issue, I was getting `C:/Users/czommerfelds/.scm_breeze/lib/git/status_shortcuts.rb:29:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)`
I uninstalled Ruby and that got fixed. Probably due to the same problem you mentioned.

**Comment by ghthor** [comment]
@zommerfelds are you saying that without ruby installed scm_breeze is now working for you on windows?

**Comment by zommerfelds** [comment]
@ghthor: yes

**Comment by zommerfelds** [comment]
@ghthor: I use it inside Git Bash (https://git-for-windows.github.io/)

**Comment by ghthor** [comment]
That seems extraordinary. Perhaps Git Bash is providing a newer version of ruby that has support for the syntax used in the scm_breeze scripts?

**Comment by zommerfelds** [comment]
No I don't think it provides any Ruby version. As far as I understand scm_breeze has a Bash (non-Ruby) version, and that one seems to work.

**Comment by zommerfelds** [comment]
@ghthor: NVM, `gb` doesn't work without Ruby `bash: ruby: command not found`

**Comment by AsaAyers** [comment]
I'm making https://github.com/pulls more useful to me today by closing my old PRs.

**Pull request closed without merging**
