### PR TITLE
Update uninstall.sh, Fixes #205

### LINKED ISSUE #205: Uninstall fails and doesn't attempt to totally clean up
The uninstall script seems to be broken on MBP (10.11.4): 

``` bash
dan@kraken:~
$ ~/.scm_breeze/uninstall.sh
sed: 1: "/Users/dan/.bashrc": extra characters at the end of d command
== Removed SCM Breeze from '/Users/dan/.bashrc'
sed: 1: "/Users/dan/.zshrc": extra characters at the end of d command
== Removed SCM Breeze from '/Users/dan/.zshrc'
```

Moreover, running the uninstall script doesn't attempt to remove the scm_breeze configuration files placed within `~` on installation:

``` bash
dan@kraken:~
$ ls -al | grep scm
-rw-r--r--    1 dan   staff   4064 May 21 14:59 .git.scmbrc
drwxr-xr-x   14 dan   staff    476 May 21 14:58 .scm_breeze
-rw-r--r--    1 dan   staff    607 May 21 14:59 .scmbrc
```

### PR DESCRIPTION
**Pull request by chrisfinazzo**
Credit to @dleve123 and @hammady for discovering this and suggesting a fix. Should alleviate one potential hurdle for #222.

### CODE REVIEW

**Comment by ghthor** [comment]
Is that fix for sed for OSX/BSD sed? I believe GNU sed doesn't require that.

**Comment by chrisfinazzo** [comment]
Yes, it is. As this is a general thing any platform could use, should this be an if/else block based on the current OS.

In addition, Shellcheck complains about variables inside of the `printf` - if this isn't a big deal I'll leave it, but otherwise I'll clean that up as well.

**Comment by ghthor** [comment]
Yes, this is used across platforms with, I suspect, Linux being the largest install base. If/Else should be added.

I'd rather has the fixes for printf is a separate PR if that isn't too much trouble.

Thanks for your work! =)

**Comment by chrisfinazzo** [comment]
Sigh. Now my repo's gone insane. Here's what I'd like to push and the error: 

screen shot 2017-01-31 at 4 53 51 pm

    $ git push origin fix-uninstall-script
    fatal: fix-uninstall-script cannot be resolved to branch.

**Comment by ghthor** [comment]
That's pretty strange!

**Comment by chrisfinazzo** [comment]
For a relatively simple merge conflict, that's the strangest thing...

Going to trash this and just cut a new branch from `master`.

**Comment by chrisfinazzo** [comment]
See #231.

**Pull request closed without merging**
