### PR TITLE
Fixed completions for 'gl' and 'gla' aliases

### LINKED ISSUE #320: Completions for 'gl' and 'gla' aliases doesn't work
Fixed them in #319

### PR DESCRIPTION
**Pull request by telzhov**
Closes #320

### CODE REVIEW

**Comment by ghthor** [comment]
This changes the argument definition from a single string into an array of strings? That seems fine to me.

**Comment by telzhov** [comment]
Right, because __git_alias function defined above in that file expects the argument list split into array:

```
__git_alias () {
    ...
    if [ $# -gt 2 ]; then
      shift 3 2>/dev/null
      cmd_args=("$@")
    fi
```

**Comment by telzhov** [comment]
Hi,
I see that this PR hasn't been accepted so far. You don't find these changes really useful, don't you?..
Thanks!

**Comment by jeffbyrnes** [comment]
Would sure be nice to have this merge in!

**Comment by ghthor** [comment]
> Hi, I see that this PR hasn't been accepted so far. You don't find these changes really useful, don't you?.. Thanks!

No, I've just been lazy

**Comment by telzhov** [comment]
> > Hi, I see that this PR hasn't been accepted so far. You don't find these changes really useful, don't you?.. Thanks!
> 
> No, I've just been lazy

Thanks a lot!

**Pull request merged**
